version: '3.8'

services:
  mongo:
    container_name: mongo
    image: 'mongo:4.4'
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  
  my-service-production:
    container_name: my-service-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
        - WS_PORT=${WEBSOCKET_PORT}
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

volumes:
  mongo:
  node_modules: