apiVersion : apps/v1
kind: Deployment
metadata:
  name: easyroadback 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easyroadback
  template:
    metadata:
      labels:
        app: easyroadback 
    spec:
      containers:
        - name: easyroadback 
          image: crtwitterauto.azurecr.io/easyroadback
          ports:
          - containerPort: 3000
          - containerPort: 3500
          env_file:
            - .env