apiVersion : apps/v1
kind: Deployment
metadata:
  name: ftsback 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftsback
  template:
    metadata:
      labels:
        app: ftsback 
        lbtype: external
    spec:
      containers:
        - name: ftsback
          image: crtwitterauto.azurecr.io/ftsback
          ports:
          - containerPort: 3500
          - containerPort: 3600
          env:
          - name: LOGGER_LEVEL
            value: "log"
          - name: PORT
            value: "3500"
          - name: DATABASE_HOST
            value: "mongodb://tfex-cosmos-db-94326:SciL2MZtKGOxDN602lSIC1VRGbXVZMZfOu6SWoZy5FH9OTI1ruSGmTWjMIGigKpL6wo8Q0NKlTgUACDbYDJLeQ==@tfex-cosmos-db-94326.mongo.cosmos.azure.com:10255/easyroad?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@tfex-cosmos-db-94326@"
          - name: WEBSOCKET_PORT
            value: "3600"
          - name: WEBSOCKET_CORS_ORIGIN
            value: "*"
          - name: AZURE_SAS_KEY
            value: sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-03-13T15:51:18Z&st=2024-03-06T07:51:18Z&spr=https,http&sig=Zq73YcShVXUyAlbXyhtFfDIPwVZToVRa20t7akm6IH8%3D
          - name: AZURE_ACCOUNT_NAME
            value: mysastorage
          - name: AZURE_CONTAINER_NAME
            value: mysccontent