apiVersion: v1
kind: Service
metadata:
    name: ftsback
spec:
    type: LoadBalancer
    ports:
        - name: http
          protocol: TCP
          port: 3500
          targetPort: 3500
        - name: ws
          protocol: ws
          port: 3600
          targetPort: 3600
    selector:
        app: ftsback